### ISSUE TITLE
[Enhancement] Add redux for state management

### ISSUE THREAD

**Issue by ankitjena** [ankitjena/whatsonyourlist#1]
We need to add redux for state management.

**Comment by StrangeNoob** [comment]
Hi @ankitjena I would love to work on this.

**Comment by ankitjena** [comment]
Sure

**Comment by ankitjena** [comment]
@StrangeNoob Update?

**Comment by ankitjena** [comment]
@StrangeNoob This issue is blocker for the rest of the issues

**Comment by StrangeNoob** [comment]
Sorry @ankitjena for the delay. #12
