### ISSUE TITLE
[Refactor] Setup apollo-server for backend

### ISSUE THREAD

**Issue by ankitjena** [ankitjena/whatsonyourlist#17]
Part 1 of #16 
Follow the tutorial in the following link to setup apollo server for backend
[https://www.robinwieruch.de/graphql-apollo-server-tutorial](https://www.robinwieruch.de/graphql-apollo-server-tutorial)

- Make PR to a branch other than master(we will merge once we have both client and server setup)
- Convert current apis to respective queries and mutations

**Comment by ganeshpatro321** [comment]
This can be closed now.
